channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - pytorch>=1.12
  - pytorch-cuda=11.7
  - transformers>=4.24.0
  - datasets>=2.6.0
  - pytorch-lightning

  - scikit-learn
  - pandas
  - wandb

  - rich
  - typer
  - loguru

  - black
  - isort
  - flake8
  - flake8-bugbear
  - mypy
  - ipywidgets
  - pre-commit

  - pip:
      - bitsandbytes; platform_system=='Linux'
